version: "3.8"

services:
  core:
    build:
      context: ./core
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    platform: linux/arm64v8
    networks:
      network:
        ipv4_address: 10.5.0.2

  data_retriever:
    build:
      context: ./data_retriever
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./data_retriever/src:/src
    platform: linux/arm64v8
    networks:
      network:
        ipv4_address: 10.5.0.3

  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      network:
        ipv4_address: 10.5.0.4

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
